/**
 * CHARRMPASS - Registration Page Logic
 * Two flows bridged by the CPASS ID:
 *   pedestrian : Personal Info -> Documents -> Review   (person gets a CPASS ID)
 *   vehicle    : Verify CPASS ID -> Vehicle Details -> Review (links vehicle to owner)
 *
 * CPASS ID rules
 *   Student            -> CPASS ID = Student ID (typed by user)
 *   Faculty/Staff/etc. -> CPASS ID auto-generated by the database: CP00, CP01 ... CP99, CP100 ...
 */

if (typeof initSupabase === 'function') {
    initSupabase();
} else {
    console.warn('supabase-config.js not loaded. Operating in fallback mode.');
}

if (typeof showToast !== 'function') {
    window.showToast = function(msg, type = 'info') {
        alert(msg);
    };
}

// =====================
// STATE
// =====================
let mode = null;               // 'pedestrian' | 'vehicle'
let flow = [];                 // ordered list of step ids for the current mode
let flowIndex = 0;
let verifiedOwner = null;      // owner row returned by lookupCpass()
let issuedCpassId = null;      // CPASS ID shown on the success screen
let cameraStream = null;
let cameraTarget = null;

const STEP_LABELS = {
    1: 'Personal Info',
    2: 'Documents',
    3: 'Vehicle Details',
    4: 'Review',
    5: 'Verify CPASS ID'
};

const FLOWS = {
    pedestrian: [1, 2, 4],
    vehicle:    [5, 3, 4]
};

// Photo data store
const photoData = {
    profile: null,
    license: null,
    idFront: null,
    idBack: null,
    motorcycle: null,
    orCr: null
};

function currentStepId() {
    return flow[flowIndex];
}

// =====================
// MODE SELECTION
// =====================
function selectMode(newMode) {
    if (!FLOWS[newMode]) return;
    mode = newMode;
    flow = FLOWS[newMode];
    flowIndex = 0;

    const url = new URL(window.location.href);
    url.searchParams.set('mode', newMode);
    window.history.replaceState({}, '', url);

    document.getElementById('modeChoice').classList.add('hidden');
    document.getElementById('formStepper').classList.remove('hidden');
    document.getElementById('registrationForm').classList.remove('hidden');
    // Hidden steps contain required fields; we validate manually per step instead.
    document.getElementById('registrationForm').noValidate = true;

    if (mode === 'pedestrian') {
        document.getElementById('pageTitle').textContent = 'Register as a Person';
        document.getElementById('pageSubtitle').textContent = 'Get your CPASS ID. You will use it to register your vehicles.';
    } else {
        document.getElementById('pageTitle').textContent = 'Register a Vehicle';
        document.getElementById('pageSubtitle').textContent = 'Link your vehicle to your approved CPASS ID.';
    }

    toggleStudentId();
    buildStepper();
    updateStepper();
}

function backToModeChoice() {
    const url = new URL(window.location.href);
    url.searchParams.delete('mode');
    window.location.href = url.pathname;
}

// =====================
// STUDENT ID / CPASS ID HELPERS
// =====================
function toggleStudentId() {
    const role = document.getElementById('regRole').value;
    const isStudent = role === 'Student';
    document.getElementById('fieldStudentId').classList.toggle('hidden', !isStudent);
    document.getElementById('fieldCpassNote').classList.toggle('hidden', isStudent || !role);
}

function normalizeCpass(value) {
    return (value || '').trim().toUpperCase();
}

function isValidStudentId(value) {
    // letters, digits and dashes, 4-20 chars (e.g. 2021-0123)
    return /^[A-Z0-9][A-Z0-9-]{3,19}$/.test(value);
}

// =====================
// STEPPER NAVIGATION
// =====================
function buildStepper() {
    const stepper = document.getElementById('formStepper');
    stepper.innerHTML = '';
    flow.forEach((stepId, i) => {
        if (i > 0) {
            const line = document.createElement('div');
            line.className = 'w-8 h-px bg-slate-300';
            stepper.appendChild(line);
        }
        const el = document.createElement('div');
        el.className = 'stepper-step';
        el.dataset.step = String(stepId);
        el.innerHTML = `<span class="step-number">${i + 1}</span><span class="hidden sm:inline">${STEP_LABELS[stepId]}</span>`;
        stepper.appendChild(el);
    });
}

function updateStepper() {
    const stepId = currentStepId();

    document.querySelectorAll('#formStepper .stepper-step').forEach((step, i) => {
        step.classList.remove('active', 'completed');
        if (i === flowIndex) step.classList.add('active');
        if (i < flowIndex) step.classList.add('completed');
    });

    // Show only the active form step
    document.querySelectorAll('.form-step').forEach(s => s.classList.add('hidden'));
    const activeStep = document.querySelector(`.form-step[data-step="${stepId}"]`);
    if (activeStep) {
        activeStep.classList.remove('hidden');
        activeStep.classList.add('animate-slide-up');
    }

    const isLast = flowIndex === flow.length - 1;
    // Previous is always available: first step goes back to the mode choice
    document.getElementById('btnPrevStep').classList.remove('hidden');
    document.getElementById('btnNextStep').classList.toggle('hidden', isLast);
    document.getElementById('btnSubmit').classList.toggle('hidden', !isLast);

    // Verify step: Next stays disabled until an owner is verified
    const nextBtn = document.getElementById('btnNextStep');
    const lockNext = stepId === 5 && !verifiedOwner;
    nextBtn.disabled = lockNext;
    nextBtn.classList.toggle('opacity-50', lockNext);
    nextBtn.classList.toggle('cursor-not-allowed', lockNext);

    if (stepId === 4) buildReview();

    lucide.createIcons();
}

function flagField(id, message) {
    const el = document.getElementById(id);
    if (el) {
        el.focus();
        el.classList.add('border-red-400');
        setTimeout(() => el.classList.remove('border-red-400'), 2000);
    }
    showToast(message, 'warning');
    return false;
}

function validateCurrentStep() {
    const stepId = currentStepId();

    if (stepId === 1) {
        const fields = ['regFullName', 'regAge', 'regSex', 'regAddress', 'regRole'];
        for (const id of fields) {
            if (!document.getElementById(id).value.trim()) {
                return flagField(id, 'Please fill in all required fields.');
            }
        }
        if (document.getElementById('regRole').value === 'Student') {
            const sid = normalizeCpass(document.getElementById('regStudentId').value);
            if (!sid) return flagField('regStudentId', 'Please enter your Student ID.');
            if (!isValidStudentId(sid)) {
                return flagField('regStudentId', 'Student ID may only use letters, numbers and dashes (4-20 characters).');
            }
        }
    }

    if (stepId === 2) {
        if (!photoData.profile) { showToast('Please upload or take your profile picture first.', 'warning'); return false; }
        if (!photoData.idFront) { showToast('Please upload the front of your ID card first.', 'warning'); return false; }
        if (!photoData.idBack)  { showToast('Please upload the back of your ID card first.', 'warning'); return false; }
    }

    if (stepId === 5) {
        if (!verifiedOwner) {
            return flagField('lookupCpassId', 'Please verify your CPASS ID first.');
        }
    }

    if (stepId === 3) {
        const fields = [
            ['regVehType', 'Please select your vehicle type.'],
            ['regVehModel', 'Please enter the vehicle model.'],
            ['regPlate', 'Please enter the plate number.'],
            ['regVehColor', 'Please enter the vehicle color.']
        ];
        for (const [id, msg] of fields) {
            if (!document.getElementById(id).value.trim()) return flagField(id, msg);
        }
    }
    return true;
}

document.getElementById('btnNextStep').addEventListener('click', () => {
    if (!validateCurrentStep()) return;
    if (flowIndex < flow.length - 1) {
        flowIndex++;
        updateStepper();
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
});

document.getElementById('btnPrevStep').addEventListener('click', () => {
    if (flowIndex > 0) {
        flowIndex--;
        updateStepper();
        window.scrollTo({ top: 0, behavior: 'smooth' });
    } else {
        backToModeChoice();
    }
});

// =====================
// CPASS ID LOOKUP (vehicle mode)
// =====================
async function lookupCpass() {
    const input = document.getElementById('lookupCpassId');
    const result = document.getElementById('lookupResult');
    const btn = document.getElementById('btnLookupCpass');
    const cpass = normalizeCpass(input.value);

    verifiedOwner = null;
    updateStepper();

    if (!cpass) {
        result.innerHTML = '';
        return flagField('lookupCpassId', 'Please enter your CPASS ID.');
    }

    const origBtn = btn.innerHTML;
    btn.disabled = true;
    btn.innerHTML = '<i data-lucide="loader-2" class="w-4 h-4 animate-spin"></i> Checking...';
    lucide.createIcons();

    try {
        let owner = null;

        if (typeof isConnected !== 'undefined' && isConnected) {
            const { data, error } = await supabaseClient
                .from('users')
                .select('id, full_name, role, program, profile_image, cpass_id, approval_status')
                .ilike('cpass_id', cpass)
                .limit(1);
            if (error) throw new Error(error.message);
            owner = (data && data[0]) || null;
        } else {
            const demo = JSON.parse(localStorage.getItem('charrmpass_registrations') || '[]');
            const found = demo.find(r => (r.cpass_id || '').toUpperCase() === cpass);
            if (found) {
                owner = { id: found.id, full_name: found.full_name, role: found.role, program: found.program,
                          profile_image: found.profile_image, cpass_id: found.cpass_id,
                          approval_status: found.approval_status || 'PENDING' };
            }
        }

        if (!owner) {
            result.innerHTML = lookupMessage('red', 'x-circle', 'CPASS ID not found',
                'Check the ID, or register as a person first to get one.');
        } else if (owner.approval_status === 'PENDING') {
            result.innerHTML = lookupMessage('amber', 'clock', 'Waiting for approval',
                `${escapeHtml(owner.full_name)}'s registration has not been approved by an administrator yet. Please come back after approval.`);
        } else if (owner.approval_status === 'REJECTED') {
            result.innerHTML = lookupMessage('red', 'ban', 'Registration rejected',
                'This account was rejected. Please contact the administrator.');
        } else {
            verifiedOwner = owner;
            const avatar = owner.profile_image ||
                'https://ui-avatars.com/api/?name=' + encodeURIComponent(owner.full_name);
            result.innerHTML = `
                <div class="flex items-center gap-4 p-4 rounded-2xl bg-green-50 border border-green-200">
                    <img src="${avatar}" alt="Owner" class="w-16 h-16 rounded-2xl object-cover border-2 border-white shadow-md">
                    <div class="flex-1">
                        <div class="text-xs font-bold text-green-700 uppercase tracking-wide flex items-center gap-1">
                            <i data-lucide="badge-check" class="w-3.5 h-3.5"></i> Verified
                        </div>
                        <div class="font-display font-bold text-lg text-slate-800">${escapeHtml(owner.full_name)}</div>
                        <div class="text-xs text-slate-500">${escapeHtml(owner.role || '')} ${owner.program ? '&bull; ' + escapeHtml(owner.program) : ''} &bull; ${escapeHtml(owner.cpass_id)}</div>
                    </div>
                </div>`;
        }
    } catch (err) {
        console.error('CPASS lookup error:', err);
        let msg = err.message || 'Lookup failed.';
        if (msg.includes('cpass_id') && msg.includes('does not exist')) {
            msg = 'Database is missing the CPASS ID column. Run supabase/migration_cpass_id.sql first.';
        }
        result.innerHTML = lookupMessage('red', 'alert-triangle', 'Lookup failed', escapeHtml(msg));
    } finally {
        btn.disabled = false;
        btn.innerHTML = origBtn;
        updateStepper();
    }
}

function lookupMessage(color, icon, title, body) {
    return `
        <div class="flex items-start gap-3 p-4 rounded-2xl bg-${color}-50 border border-${color}-200">
            <i data-lucide="${icon}" class="w-5 h-5 text-${color}-600 mt-0.5"></i>
            <div>
                <div class="text-sm font-bold text-${color}-700">${title}</div>
                <div class="text-xs text-slate-600 mt-0.5">${body}</div>
            </div>
        </div>`;
}

function escapeHtml(str) {
    return String(str == null ? '' : str).replace(/[&<>"']/g, c => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    }[c]));
}

// Changing the typed ID invalidates the previous verification
document.getElementById('lookupCpassId').addEventListener('input', () => {
    if (verifiedOwner) {
        verifiedOwner = null;
        document.getElementById('lookupResult').innerHTML = '';
        updateStepper();
    }
});
document.getElementById('lookupCpassId').addEventListener('keydown', (e) => {
    if (e.key === 'Enter') { e.preventDefault(); lookupCpass(); }
});

// =====================
// CAMERA FUNCTIONALITY
// =====================
function openCamera(target) {
    cameraTarget = target;
    const modal = document.getElementById('cameraModal');
    const video = document.getElementById('cameraVideo');

    modal.classList.remove('hidden');

    navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user', width: 640, height: 480 } })
        .then(stream => {
            cameraStream = stream;
            video.srcObject = stream;
        })
        .catch(err => {
            console.error('Camera error:', err);
            showToast('Could not access camera. Please use upload instead.', 'error');
            closeCamera();
        });
}

function closeCamera() {
    const modal = document.getElementById('cameraModal');
    const video = document.getElementById('cameraVideo');

    if (cameraStream) {
        cameraStream.getTracks().forEach(track => track.stop());
        cameraStream = null;
    }
    video.srcObject = null;
    modal.classList.add('hidden');
}

function capturePhoto() {
    const video = document.getElementById('cameraVideo');
    const canvas = document.getElementById('cameraCanvas');

    const MAX = 600;
    let w = video.videoWidth || 640;
    let h = video.videoHeight || 480;
    if (w > MAX || h > MAX) {
        if (w > h) { h = Math.round(h * MAX / w); w = MAX; }
        else { w = Math.round(w * MAX / h); h = MAX; }
    }

    canvas.width = w;
    canvas.height = h;
    canvas.getContext('2d').drawImage(video, 0, 0, w, h);

    // Compress to smaller size for DB storage
    const dataUrl = canvas.toDataURL('image/jpeg', 0.6);
    photoData[cameraTarget] = dataUrl;

    updatePhotoPreview(cameraTarget, dataUrl);
    closeCamera();
    showToast('Photo captured successfully!', 'success');
}

// =====================
// FILE UPLOAD
// =====================
function handleFileUpload(input, target) {
    const file = input.files[0];
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
        showToast('File too large. Maximum 5MB allowed.', 'error');
        return;
    }

    // Resize image before storing
    const reader = new FileReader();
    reader.onload = (e) => {
        const img = new Image();
        img.onload = () => {
            const canvas = document.createElement('canvas');
            const MAX = 400;
            let w = img.width, h = img.height;
            if (w > MAX || h > MAX) {
                if (w > h) { h = Math.round(h * MAX / w); w = MAX; }
                else { w = Math.round(w * MAX / h); h = MAX; }
            }
            canvas.width = w; canvas.height = h;
            canvas.getContext('2d').drawImage(img, 0, 0, w, h);
            const compressed = canvas.toDataURL('image/jpeg', 0.5);
            photoData[target] = compressed;
            updatePhotoPreview(target, compressed);
            showToast('Photo uploaded successfully!', 'success');
        };
        img.src = e.target.result;
    };
    reader.readAsDataURL(file);
}

function updatePhotoPreview(target, dataUrl) {
    const previewMap = {
        profile: 'profilePhotoPreview',
        license: 'licensePreview',
        idFront: 'idFrontPreview',
        idBack: 'idBackPreview',
        motorcycle: 'motorcyclePreview',
        orCr: 'orCrPreview'
    };

    const container = document.getElementById(previewMap[target]);
    if (!container) return;

    if (target === 'profile') {
        container.innerHTML = `<img src="${dataUrl}" alt="${target}" class="w-full h-full object-cover">`;
    } else {
        container.innerHTML = `<img src="${dataUrl}" alt="${target}" class="w-full h-40 object-cover rounded-lg">`;
        container.parentElement.classList.add('has-image');
    }

    lucide.createIcons();
}

// =====================
// MOTORCYCLE TOGGLE
// =====================
function toggleMotorcyclePhoto() {
    const type = document.getElementById('regVehType').value;
    const section = document.getElementById('motorcyclePhotoSection');
    section.classList.toggle('hidden', type !== 'Motorcycle');
}

// =====================
// BUILD REVIEW
// =====================
function reviewTile(label, value) {
    return `
        <div class="p-3 bg-white/60 rounded-xl border border-slate-100">
            <div class="text-[10px] font-bold text-slate-400 uppercase tracking-wide">${label}</div>
            <div class="text-sm font-bold text-slate-800 mt-1">${escapeHtml(value || '--')}</div>
        </div>`;
}

function thumbnails(docs) {
    let html = '<div class="mt-4"><div class="text-xs font-bold text-slate-400 uppercase tracking-wide mb-2">Uploaded Documents</div><div class="flex gap-3 flex-wrap">';
    for (const [label, img] of Object.entries(docs)) {
        if (img) {
            html += `<div class="text-center"><img src="${img}" alt="${label}" class="w-16 h-16 rounded-lg object-cover border border-slate-200 shadow-sm"><div class="text-[10px] font-bold text-slate-400 mt-1">${label}</div></div>`;
        } else {
            html += `<div class="text-center"><div class="w-16 h-16 rounded-lg bg-slate-100 border border-dashed border-slate-300 flex items-center justify-center text-slate-300"><i data-lucide="image-off" class="w-6 h-6"></i></div><div class="text-[10px] font-bold text-slate-400 mt-1">${label} (skipped)</div></div>`;
        }
    }
    return html + '</div></div>';
}

function buildReview() {
    const reviewContent = document.getElementById('reviewContent');
    let html = '';

    if (mode === 'pedestrian') {
        const name = document.getElementById('regFullName').value;
        const role = document.getElementById('regRole').value;
        const isStudent = role === 'Student';
        const studentId = normalizeCpass(document.getElementById('regStudentId').value);

        html += `
            <div class="flex items-start gap-5 p-4 bg-white/60 rounded-2xl border border-slate-100">
                <img src="${photoData.profile || 'https://ui-avatars.com/api/?name=' + encodeURIComponent(name)}" alt="Profile" class="w-20 h-20 rounded-2xl object-cover border-2 border-white shadow-md">
                <div>
                    <div class="text-xl font-display font-bold text-slate-800">${escapeHtml(name)}</div>
                    <div class="flex items-center gap-2 mt-1">
                        <span class="px-2.5 py-0.5 rounded text-xs font-bold bg-charm-dark text-white uppercase">${escapeHtml(role)}</span>
                        <span class="text-sm text-slate-500">${escapeHtml(document.getElementById('regProgram').value || '--')} &bull; ${escapeHtml(document.getElementById('regSection').value || '--')}</span>
                    </div>
                    <div class="text-xs text-slate-400 mt-1">${escapeHtml(document.getElementById('regAge').value)} years old &bull; ${escapeHtml(document.getElementById('regSex').value)}</div>
                </div>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                ${reviewTile('Address', document.getElementById('regAddress').value)}
                ${reviewTile('Your CPASS ID', isStudent ? studentId + ' (your Student ID)' : 'Generated after you submit (e.g. CP07)')}
            </div>`;
        html += thumbnails({ 'Profile': photoData.profile, 'ID Front': photoData.idFront, 'ID Back': photoData.idBack });
    } else {
        const avatar = (verifiedOwner && verifiedOwner.profile_image) ||
            'https://ui-avatars.com/api/?name=' + encodeURIComponent(verifiedOwner ? verifiedOwner.full_name : '?');
        html += `
            <div class="flex items-center gap-4 p-4 bg-white/60 rounded-2xl border border-slate-100">
                <img src="${avatar}" alt="Owner" class="w-16 h-16 rounded-2xl object-cover border-2 border-white shadow-md">
                <div>
                    <div class="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Vehicle Owner</div>
                    <div class="text-lg font-display font-bold text-slate-800">${escapeHtml(verifiedOwner ? verifiedOwner.full_name : '--')}</div>
                    <div class="text-xs text-slate-500">CPASS ID: <b>${escapeHtml(verifiedOwner ? verifiedOwner.cpass_id : '--')}</b></div>
                </div>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-3 gap-4 mt-4">
                ${reviewTile('Vehicle Type', document.getElementById('regVehType').value)}
                ${reviewTile('Vehicle Model', document.getElementById('regVehModel').value)}
                ${reviewTile('Plate Number', document.getElementById('regPlate').value.toUpperCase())}
                ${reviewTile('Vehicle Color', document.getElementById('regVehColor').value)}
            </div>`;
        html += thumbnails({ 'OR/CR': photoData.orCr, "License": photoData.license, 'Motorcycle': photoData.motorcycle });
    }

    reviewContent.innerHTML = html;
    lucide.createIcons();
}

// =====================
// FORM SUBMISSION
// =====================
function isDbConnected() {
    return typeof isConnected !== 'undefined' && isConnected;
}

async function submitPedestrian() {
    const role = document.getElementById('regRole').value;
    const isStudent = role === 'Student';
    const studentId = isStudent ? normalizeCpass(document.getElementById('regStudentId').value) : null;

    const base = {
        full_name:             document.getElementById('regFullName').value.trim(),
        age:                   parseInt(document.getElementById('regAge').value),
        sex:                   document.getElementById('regSex').value,
        address:               document.getElementById('regAddress').value.trim(),
        role:                  role,
        program:               document.getElementById('regProgram').value.trim() || null,
        section:               document.getElementById('regSection').value.trim() || null,
        default_transit_mode:  'PEDESTRIAN',
        profile_image:         photoData.profile  || null,
        id_front_image:        photoData.idFront  || null,
        id_back_image:         photoData.idBack   || null,
    };

    if (isDbConnected()) {
        const payload = { ...base, approval_status: 'PENDING' };
        if (isStudent) {
            payload.student_id = studentId;
            payload.cpass_id = studentId;       // Student ID IS the CPASS ID
        }
        // Non-students: omit cpass_id, the DB trigger assigns CP00, CP01, ...

        const { data: newUser, error: userErr } = await supabaseClient
            .from('users')
            .insert([payload])
            .select()
            .single();
        if (userErr) throw new Error(userErr.message);

        // Close-range card placeholder: admin assigns the real UID after approval
        const { error: cardErr } = await supabaseClient
            .from('rfid_cards')
            .insert([{
                rfid_uid:             'UNASSIGNED_' + Date.now(),
                user_id:              newUser.id,
                vehicle_id:           null,
                rfid_type:            'CLOSE_RANGE',
                user_type:            'PEDESTRIAN',
                authorization_status: 'PENDING',
            }]);
        if (cardErr) {
            await supabaseClient.from('users').delete().eq('id', newUser.id);
            throw new Error('RFID card insert failed: ' + cardErr.message);
        }

        return newUser.cpass_id;
    }

    // Demo mode (localStorage)
    const registrations = JSON.parse(localStorage.getItem('charrmpass_registrations') || '[]');
    let cpass = studentId;
    if (!cpass) {
        const n = registrations.filter(r => /^CP\d+$/.test(r.cpass_id || '')).length;
        cpass = 'CP' + (n < 10 ? '0' + n : String(n));
    }
    registrations.push({
        id: 'local_' + Date.now(),
        created_at: new Date().toISOString(),
        ...base,
        cpass_id: cpass,
        student_id: studentId,
        user_type: 'PEDESTRIAN',
        rfid_type: 'CLOSE_RANGE',
        authorization_status: 'PENDING',
        approval_status: 'PENDING'
    });
    localStorage.setItem('charrmpass_registrations', JSON.stringify(registrations));
    showToast('Registration saved locally (Demo Mode).', 'info');
    return cpass;
}

async function submitVehicle() {
    if (!verifiedOwner) throw new Error('Please verify your CPASS ID first.');

    const vehicle = {
        vehicle_type:     document.getElementById('regVehType').value,
        vehicle_model:    document.getElementById('regVehModel').value.trim(),
        plate_number:     document.getElementById('regPlate').value.toUpperCase().trim(),
        vehicle_color:    document.getElementById('regVehColor').value.trim(),
        motorcycle_image: photoData.motorcycle || null,
        or_cr_image:      photoData.orCr || null,
    };

    if (isDbConnected()) {
        const { data: newVehicle, error: vehErr } = await supabaseClient
            .from('vehicles')
            .insert([{ user_id: verifiedOwner.id, approval_status: 'PENDING', ...vehicle }])
            .select()
            .single();
        if (vehErr) throw new Error(vehErr.message);

        // Driver's license is stored on the owner's profile when provided
        if (photoData.license) {
            await supabaseClient.from('users')
                .update({ drivers_license_image: photoData.license })
                .eq('id', verifiedOwner.id);
        }

        // UHF sticker placeholder: admin assigns the real UID after approval
        const { error: cardErr } = await supabaseClient
            .from('rfid_cards')
            .insert([{
                rfid_uid:             'UNASSIGNED_' + Date.now(),
                vehicle_id:           newVehicle.id,
                user_id:              verifiedOwner.id,
                rfid_type:            'LONG_RANGE',
                user_type:            'VEHICLE',
                authorization_status: 'PENDING',
            }]);
        if (cardErr) {
            await supabaseClient.from('vehicles').delete().eq('id', newVehicle.id);
            throw new Error('RFID card insert failed: ' + cardErr.message);
        }
        return;
    }

    // Demo mode (localStorage)
    const registrations = JSON.parse(localStorage.getItem('charrmpass_registrations') || '[]');
    registrations.push({
        id: 'local_' + Date.now(),
        created_at: new Date().toISOString(),
        full_name: verifiedOwner.full_name,
        role: verifiedOwner.role,
        cpass_id: verifiedOwner.cpass_id,
        default_transit_mode: 'VEHICLE',
        user_type: 'VEHICLE',
        rfid_type: 'LONG_RANGE',
        ...vehicle,
        plate_number: vehicle.plate_number,
        authorization_status: 'PENDING',
        approval_status: 'PENDING'
    });
    localStorage.setItem('charrmpass_registrations', JSON.stringify(registrations));
    showToast('Vehicle saved locally (Demo Mode).', 'info');
}

function showSuccess() {
    document.getElementById('registrationForm').classList.add('hidden');
    document.getElementById('formStepper').classList.add('hidden');
    document.getElementById('successMessage').classList.remove('hidden');

    const text = document.getElementById('successText');
    if (mode === 'pedestrian') {
        document.getElementById('pageTitle').textContent = 'You are registered!';
        document.getElementById('pageSubtitle').textContent = 'Save your CPASS ID below';
        text.textContent = 'An administrator will review and approve your account. Once approved, use your CPASS ID to register your vehicles.';
        document.getElementById('cpassValue').textContent = issuedCpassId || '--';
        document.getElementById('cpassCard').classList.remove('hidden');
        document.getElementById('btnRegisterVehicleNext').classList.remove('hidden');
    } else {
        document.getElementById('pageTitle').textContent = 'Vehicle submitted!';
        document.getElementById('pageSubtitle').textContent = 'Waiting for administrator approval';
        text.textContent = 'Your vehicle is linked to your CPASS ID. After approval, the administrator will issue your UHF sticker.';
    }
    lucide.createIcons();
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

function copyCpassId() {
    if (!issuedCpassId) return;
    const done = () => showToast('CPASS ID copied: ' + issuedCpassId, 'success');
    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(issuedCpassId).then(done).catch(done);
    } else {
        const tmp = document.createElement('textarea');
        tmp.value = issuedCpassId;
        document.body.appendChild(tmp);
        tmp.select();
        document.execCommand('copy');
        document.body.removeChild(tmp);
        done();
    }
}

document.getElementById('registrationForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    if (!validateCurrentStep()) return;

    const btnSubmit = document.getElementById('btnSubmit');
    const origText = btnSubmit.innerHTML;
    btnSubmit.innerHTML = '<i data-lucide="loader-2" class="w-4 h-4 animate-spin"></i> Submitting...';
    btnSubmit.disabled = true;
    lucide.createIcons();

    try {
        if (mode === 'pedestrian') {
            issuedCpassId = await submitPedestrian();
        } else {
            await submitVehicle();
        }
        showToast('Registration submitted! Awaiting admin approval.', 'success');
        showSuccess();
    } catch (err) {
        console.error('Registration error:', err);
        let errMsg = err.message || err.details || 'Registration failed. Please try again.';
        const lower = errMsg.toLowerCase();
        if (errMsg.includes('vehicles_plate_number_key')) {
            errMsg = 'This license plate is already registered in the system.';
        } else if (errMsg.includes('users_cpass_id_key') || (lower.includes('duplicate key') && lower.includes('cpass'))) {
            errMsg = 'This Student ID is already registered. If it is yours, use it as your CPASS ID to register your vehicle.';
        } else if (lower.includes('duplicate key')) {
            errMsg = 'This record already exists in the system.';
        } else if (lower.includes('cpass_id') || lower.includes('approval_status') || lower.includes('or_cr_image')) {
            errMsg = 'Database is not updated yet. Run supabase/migration_cpass_id.sql in the Supabase SQL Editor.';
        } else if (errMsg.includes('violates foreign key')) {
            errMsg = 'Database relationship error. Please check your inputs.';
        }
        showToast(errMsg, 'error');
        btnSubmit.innerHTML = origText;
        btnSubmit.disabled = false;
        lucide.createIcons();
    }
});

// =====================
// INIT
// =====================
(function init() {
    const requested = new URLSearchParams(window.location.search).get('mode');
    if (requested && FLOWS[requested]) {
        selectMode(requested);
    }
    lucide.createIcons();
})();
